name: Docker Image CI

on:
  push:
    branches:
      - "main"

    paths:
      - ".github/workflows/docker-image.yml"
      - "image-builder/docker-entrypoint.sh"
      - "image-builder/Dockerfile"

env:
  REGISTRY: ghcr.io
  REGISTRY_PATH: lesscodex/pkg
  REGISTRY_USERNAME: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build -t image image-builder/

      - name: Login to registry
        if: success()
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Publish the Docker image
        if: success()
        run: |
          IMAGE_ID=$REGISTRY/$REGISTRY_PATH/openwrt:imagebuilder-23.05.4
          docker tag image $IMAGE_ID
          docker push $IMAGE_ID
